<<<<<<< HEAD
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
=======
import { cn } from '@/lib/utils'
import { interSans } from '../../styles/fonts'
import './globals.css'
//themeProvider para el dark mode
import { ThemeProvider } from '../_components/theme-provider'
//providers parametrado en otro fichero para el idioma
//import SEO from '../_components/SEO/SEO'
import { SpeedInsights } from '@vercel/speed-insights/next'
import { Metadata } from 'next'
//cuidado con estos dos imports no los importas por que next se actuamlizo
//import Head from 'next/head'
//import StructuredData from '../_components/RichSnippets/StructuredData'
import StructuredData from '../_components/RichSnippets/StructuredData'
import TopBanner from '../_components/top-banner/TopBanner'
import Providers from './providers'

import { ReactElement } from 'react'
export const metadata: Metadata = {
  title: 'Hardy Lino . Frontend Developer',
  description: 'Frontend developer, React, Next.js, TypeScript',
  metadataBase: new URL('https://hardylino.com'), // Agrega la URL base aquí
  icons: {
    icon: '/favicon.ico',
    apple: '/apple-touch-icon.png',
  },
  keywords: [
    'Frontend developer',
    'développeur frontend',
    'desarrollador frontend',
    'développeur React',
    'React',
    'Next.js',
    'Tailwind CSS',
    'Sass',
    'développeur',
    "développeur d'applications web",
    'intégrateur web',
    'création de sites vitrines',
  ],
  openGraph: {
    siteName: 'Hardy Lino',
    title: 'Hardy Lino Frontend Developer',
    description: 'Frontend developer, React, Next.js, TypeScript',
    url: 'https://hardylino.com/',
    type: 'website',
    locale: 'fr_FR',
    images: [
      {
        url: 'https://www.hardylino.com/images/port-1.jpg',
        width: 1200,
        height: 630,
        alt: 'Hardy Lino',
        type: 'image/jpg',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Hardy Lino . Frontend Developer',
    description: 'Frontend developer, React, Next.js, TypeScript',
    images: ['https://www.hardylino.com/images/port-1.jpg'],
  },
  alternates: {
    canonical: 'https://hardylino.com/',
    languages: {
      es: 'https://hardylino.com/es',
      en: 'https://hardylino.com/en',
      fr: 'https://hardylino.com/fr',
    },
  },
>>>>>>> optimize-render-blocking
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
<<<<<<< HEAD
    <html lang="en">
      <body>{children}</body>
=======
    <html lang={params.locale} className="h-full" suppressHydrationWarning>
      <body className={cn(interSans.className, 'antialiased')}>
        <StructuredData />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TopBanner />
          <Providers params={Promise.resolve({ locale: params.locale })}>
            {children}
          </Providers>
        </ThemeProvider>

        <div id="modal-root"></div>
        <SpeedInsights />
      </body>
>>>>>>> optimize-render-blocking
    </html>
  )
}
